### ISSUE TITLE
Wrong file name since Pandoc 2.8

### ISSUE THREAD

**Issue by josineto** [ashwinvis/aur#1]
Hello! Since [Pandoc 2.8](https://github.com/jgm/pandoc/releases/tag/2.8), the file for Arch Linux is `pandoc-${pkgver}-linux-amd64.tar.gz`. Note the `-amd64` part.

**Comment by ashwinvis** [comment]
Very delayed thanks for the info. I think I fixed it at some point, but it is irrelevant now because I was maintaining only https://aur.archlinux.org/packages/haskell-pandoc-citeproc-bin/ which is deprecated anyway.
